version: '3.4'

services:
  catalogdb:
    image: mongo

  salesservice.catalog.api:
    image: ${DOCKER_REGISTRY-}salesservicecatalogapi
    build:
      context: .
      dockerfile: SalesService.Catalog.API/Dockerfile

volumes:
  mongo_data: